### ISSUE TITLE
[BUG] Connection aborted if host/docker booted without ipv6

### ISSUE THREAD

**Issue by glensc** [linuxserver/docker-your_spotify#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

caused by the `::` listen:

```
/config/nginx/site-confs/default.conf:    listen [::]:80 default_server;
/config/nginx/site-confs/default.conf:    listen [::]:443 ssl http2 default_server;
```

the documentation does not mention mounting `/config`:
- https://docs.linuxserver.io/images/docker-your_spotify/#application-setup 

but it seems to be useful, then users could modify the nginx config there.

### Steps To Reproduce

boot kernel with `ipv6.disable=1`:

```
$ cat /proc/cmdline 
... ipv6.disable=1 ...
```

### Environment

- OS: Debian Bookworm
- How docker service was installed: OS package

### CPU architecture

arm64

### Docker creation

nothing specific, default config from readme

```yml
# https://docs.linuxserver.io/images/docker-your_spotify/

version: "3"

services:
  your_spotify:
    image: lscr.io/linuxserver/your_spotify:latest
    container_name: your_spotify
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Tallinn
      - APP_URL=http://localhost:1234
      - SPOTIFY_PUBLIC=
      - SPOTIFY_SECRET=
      - CORS=http://localhost:80,https://localhost:443,http://localhost:1234
      - MONGO_ENDPOINT=mongodb://mongo:27017/your_spotify
    ports:
      - 1234:80
    restart: unless-stopped

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

networks:
  default:
    external:
      name: mediaserver

# vim:ts=2:sw=2:et
```

### Container logs

```
...
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
```
```
